FROM picpay/php:7.2-fpm-base

ENTRYPOINT ["/bin/sh", "/run/docker-swoole.sh"]

ARG APP_STAGE
ENV APP_STAGE $APP_STAGE

ARG COMPOSER_AUTH
ENV COMPOSER_AUTH $COMPOSER_AUTH

ENV PECL_RBKAFKA_VERSION='3.1.1'
ENV LIB_RDKAFKA_VERSION='v1.3.0'

# Copy Files 
COPY --chown=www-data:www-data docker/config/ /
COPY --chown=www-data:www-data ./api .
COPY docker/run/ /run/
     
RUN set -ex \
    && apk add autoconf git gcc g++ make bash \  
    # Install Kafka Lib
    && git clone --depth 1 --branch ${LIB_RDKAFKA_VERSION} https://github.com/edenhill/librdkafka.git \
    && cd librdkafka \
    && ./configure \
    && make \
    && make install \
    && pecl install rdkafka-${PECL_RBKAFKA_VERSION} \
    && docker-php-ext-enable rdkafka \
    && cd ../ \
    # Install Swoole 
    && pecl install swoole \
    && touch /usr/local/etc/php/conf.d/swoole.ini \
    && echo 'extension=swoole.so' > /usr/local/etc/php/conf.d/swoole.ini \
    # requires mongo-ext 1.5.1 and Others Extensions
    && pecl install -f mongodb-1.5.1 \
    && pecl install -f timezonedb  \
    && echo 'extension=timezonedb.so' > /usr/local/etc/php/conf.d/timezonedb.ini \
    && docker-php-ext-install bcmath \
    # Configure NewRelic 
    && if [ "$APP_STAGE" != "dev" ] ; then \
    mkdir -p /etc/default \
    && curl -sS "https://download.newrelic.com/php_agent/archive/8.7.0.242/newrelic-php5-8.7.0.242-linux.tar.gz" | tar -C /tmp -zx \
    && export NR_INSTALL_USE_CP_NOT_LN=1 \
    && export NR_INSTALL_SILENT=1 \
    && /tmp/newrelic-php5-*/newrelic-install install \
    && cp /etc/newrelic/newrelic.cfg.template /etc/newrelic/newrelic.cfg \
    && mkdir /lib64 \
    && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2 ; \
    fi \
    # Configure Docker Artisan commando Batchs
    && chmod +x /run/docker-entrypoint.sh \
    && chmod +x /run/docker-artisan-env.sh \
    && ln -s /run/docker-artisan-env.sh /docker-artisan-env 
