#!/bin/bash

cd `dirname $0`

repo_root="../.."
target_container="api.promo.dev"
target_container_mongo="mongo.promo.dev"

exec () {
    docker exec -it $target_container sh
}

migrate () {
    docker exec -it $target_container php artisan migrate
}

test () {
    docker exec -it $target_container vendor/bin/phpunit "$@" || true
    docker exec -it $target_container_mongo mongo promo_test --eval "db.dropDatabase()"
}

docs () {
    docker exec -it $target_container php artisan swagger-lume:generate
}

source ${repo_root}/.service.base