route:
    repeat_interval: 30m
    group_interval: 30m
    receiver: 'curso1'

receivers:
    - name: 'curso1'
      webhook_configs:
          - send_resolved: false
            url: 'INCOMING_WEBHOOK'
